#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   w <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    w holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

cd "$PROJECTS/$1"
